name: BeaconLabsCore
version: '${project.version}'
main: org.bcnlab.beaconlabscore.BeaconLabsCore
author: ItsBeacon
api-version: '1.21'
commands:
  fly:
    description: Toggles fly mode.
    usage: /fly [nonotify]
  core:
    description: Returns basic plugin information
    usage: /core
    aliases: [beaconlabscore, labscore]
  heal:
    description: Heals a player
    usage: /heal [player] [nonotify]
  gamemode:
    description: Changes a players gamemode
    usage: /gamemode 0/1/2/3 [player] [nonotify]
    aliases: [gm, mode]
  invsee:
    description: View another player's inventory.
    usage: /invsee <player>
  workbench:
    description: Use a portable workbench.
    usage: /workbench
    aliases: [wb]
  enderchest:
    description: Use a portable enderchest.
    usage: /enderchest
    aliases: [ec]
  vanish:
    description: Hide yourself from other players
    usage: /vanish [player]
    aliases: [v]
  tp:
    description: Teleport to a player or teleport players
    usage: /tp <player> [to_player]
    aliases: [teleport]
  tphere:
    description: Teleport a player to you
    usage: /tphere <player>
    aliases: [tph]
  spectate:
    description: Spectates a player while being invisible
    usage: /spectate <player>
    aliases: [spec]
  endspectate:
    description: Ends spectator mode
    usage: /endspectate
    aliases: [espec]
  chatsudo:
    description: Sends chat messages as another player
    usage: /chatsudo <player> <message>
    aliases: [csudo]
  sudo:
    description: Executes commands as another player
    usage: /sudo <player> <command>
  serverbroadcast:
    description: Broadcast a message to the entire server (not proxywide!)
    usage: /serverbroadcast <message>
    aliases: [sbc]
  weather:
    description: Change the weather
    usage: /weather <clear|rain|storm>
    aliases: [w]
  clear:
    description: Change the weather to clear
    usage: /clear
  rain:
    description: Change the weather to rain
    usage: /rain
  storm:
    description: Change the weather to storm
    usage: /storm
  time:
    description: Change the time
    usage: /time <value|day|night|midnight|noon>
  day:
    description: Set the time to day
    usage: /day
  night:
    description: Set the time to night
    usage: /night
  midnight:
    description: Set the time to midnight
    usage: /midnight
  noon:
    description: Set the time to noon
    usage: /noon
  globalmute:
    description: Mute the entire chat
    usage: /globalmute
    aliases: [gmute]
  btps:
    description: Returns the servers TPS
    usage: /btps
  clearinventory:
    description: Clears the inventory of players
    usage: /clearinventory [player]
    aliases: [clearinv, cinv]
  clearlag:
    description: Removes entities to preserver preformance
    usage: /clearlag
    aliases: [clag]
  tpa:
    description: Allows a user to request to teleport to someone else
    usage: /tpa <player>
  tpaccept:
    description: Accept a teleportation request
    usage: /tpaccept <player>
  tpdeny:
    description: Deny a teleportation request
    usage: /tpdeny <player>
  randomteleport:
    description: Teleport to a random location on the world
    usage: /randomteleport
    aliases: [rtp]
  teleportcoordinates:
    description: Teleports the user to specific coordinates
    usage: /tpc (player) <x> <y> <z>
    aliases: [tpc, teleportc]
permissions:
  beaconlabs.core.vanish.self:
    description: Allows a player to vanish themselves.
    default: op
  beaconlabs.core.vanish.others:
    description: Allows a player to vanish other players.
    default: op
  beaconlabs.core.vanish.see:
    description: Allows a player to see vanished players.
    default: op
  beaconlabs.core.enderchest:
    description: Allows access to the enderchest command.
    default: op
  beaconlabs.core.gamemode.self:
    description: Allows changing your own game mode.
    default: op
  beaconlabs.core.gamemode.others:
    description: Allows changing other players' game modes.
    default: op
  beaconlabs.core.sudo:
    description: Allows executing commands as other players
    default: op
  beaconlabs.core.csudo:
    description: Allows sending messages as other players
    default: op
  beaconlabs.core.tp:
    description: Allows teleporting players
    default: op
  beaconlabs.core.info:
    description: Allows to return info about the plugin
    default: not op
  beaconlab.core.broadcast:
    description: Allows the user to broadcast messages serverwide (not proxywide!)
    default: op
  beaconlabs.core.weather:
    description: Allows a user to change the weather
    default: op
  beaconlabs.core.time:
    description: Allows a user to change the time
    default: op
  beaconlabs.core.globalmute.set:
    description: Enable global mute
    default: op
  beaconlabs.core.globalmute.ignore:
    description: Ignore global mute
    default: op
  beaconlabs.core.spectate:
    description: Spectate other players
    default: op
  beaconlabs.core.endspectate:
    description: End the spec mode
    default: op
  beaconlabs.core.tpa:
    description: Allows the user to send a tpa request to other users
    default: not op
  beaconlabs.core.tpaccept:
    description: Allows users to accept tpa requests
    default: not op
  beaconlabs.core.tpdeny:
    description: Allows users to deny tpa requests
    default: not op
  beaconlabs.core.rtp:
    description: Allows a user to random teleport in the world
    default: not op